[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "warranty"
version = "0.1.0"
description = "Warranty plugin for InvenTree"
readme = { text = "Warranty plugin for InvenTree.", content-type = "text/plain" }  # or file=...
requires-python = ">=3.11"
license = { text = "BSD-2-Clause" }
authors = [{ name = "John Doe" }]
keywords = ["inventree", "plugin"]
# If your plugin code uses these (it does):
dependencies = ["requests", "python-dateutil"]

[project.entry-points."inventree_plugins"]
warranty = "warranty.core:Warranty"

[tool.ruff]
exclude = [".git","__pycache__","test.py","tests","venv","env",".venv",".env"]
src = ["warranty"]